name: betlas
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - numpy
  - pandas
  - scipy
  - biopython
  - scikit-learn
  - joblib
  - tqdm
  - hydra-core
  - opencv
  - dssp
  - xgboost
  - pytest
  - ruff
