<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <StartupObject>betaBarrelProgram.ExternalBaselinePolarBearal3Cli</StartupObject>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../tools/PolarBearal3/*.cs" Exclude="../tools/PolarBearal3/AlignPDB.cs" />
    <Compile Include="PolarBearal3Cli.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
  </ItemGroup>
</Project>
